name: my_car_forum
description: A simple car forum web application.

# Update SDK version to support the latest Flutter releases
environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated from 2.18.0 < 3.0.0 to support Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  # Required for Material and Widgets localizations

  # State Management
  provider: ^6.0.0  # Stable version, consider ^6.1.0 if available

  # Media and Video
  video_player: ^2.9.1  # Check pub.dev for the latest version (e.g., ^2.9.2)

  # Storage and Preferences
  shared_preferences: ^2.3.2  # Stable, consider ^2.3.3 if released
  flutter_cache_manager: ^3.4.1  # Ensure compatibility with Flutter 3.x

  # HTTP and Networking
  http: ^1.2.1  # Consider upgrading to ^1.2.2 if available on pub.dev

  # Internationalization and For  matting
  intl: ^0.19.0  # Stable, check for ^0.20.2 or higher

  # Media and File Handling
  image_picker: ^1.1.2  # Stable, check for ^1.1.3 if available
  html: ^0.15.0  # Stable, consider ^0.15.4 if released

  # Environment and Configuration
  flutter_dotenv: ^5.2.1  # Stable, check for ^5.3.0 if available

  # Calendar and UI
  table_calendar: ^3.0.0  # Consider upgrading to ^3.1.0 if released

  # Utilities
  url_launcher: ^6.1.6  # Stable, check for ^6.2.0 if available
  xml: ^5.0.0  # Stable, consider ^6.0.0 if released

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Check pub.dev for the latest version (e.g., ^5.0.1)

# Dependency overrides for resolving version conflicts (if needed)
# dependency_overrides:
#   some_package: any  # Uncomment and adjust if conflicts arise

flutter:
  uses-material-design: true

  # Asset configuration with organized structure
  assets:
    - assets/pictures/intro.jpg
    - assets/pictures/card1.jpg
    - assets/pictures/card2.jpg
    - assets/pictures/card3.jpg
    - assets/pictures/card4.jpg
    - assets/pictures/car1.jpg
    - assets/pictures/car2.jpg
    - assets/pictures/car3.jpg
    - assets/pictures/car4.jpg
    - assets/pictures/electric_cars.jpg
    - assets/pictures/suvs.jpg
    - assets/pictures/car_of_the_year.jpg
    - assets/pictures/honda_prelude.jpg      # Feature article image
    - assets/pictures/mclaren_hypercar.jpg   # Article grid image 1
    - assets/pictures/bmw_z4.jpg             # Article grid image 2
    - assets/pictures/mustang_f100.jpg       # Article grid image 3
    - assets/pictures/hummer_rivian.jpg      # Article grid image 4
    - assets/pictures/toyota_suv.jpg
    - assets/pictures/ferrari_suv.jpg
    - assets/pictures/porsche_gt3rs.jpg      # New article 1
    - assets/pictures/tesla_cybertruck.jpg   # New article 2
    - assets/pictures/audi_a9.jpg            # New article 3
    - assets/pictures/bronco_raptor.jpg      # New article 4
    - assets/pictures/lamborghini_revuelto.jpg  # New article 5
    - assets/pictures/jeep_grand_cherokee.jpg   # New article 6
    - assets/pictures/logo.png
    - assets/pictures/ferrari_future.jpg
    - assets/pictures/bmw_i8.jpg
    - assets/pictures/tesla_roadster.jpg
    - assets/pictures/lamborghini_aventador.jpg
    - assets/pictures/default_car.jpg
    - assets/logos/  # Include the logos directory for all files inside

  # Optional: Font configuration (if you use custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/custom_font.ttf