name: my_car_forum
description: A simple car forum web application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.0.0
  http: ^1.4.0
  intl: 0.19.0
  cached_network_image: ^3.4.1 
  shared_preferences: ^2.5.3  
  flutter_dotenv: ^5.2.1      
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  url_launcher_plus: ^1.2.0
  material_design_icons_flutter: ^7.0.7296
  file_picker: ^10.1.9
  image: ^4.5.4
  path_provider: ^2.1.5
  tflite: ^1.1.2
  universal_io: ^2.2.2
  http_parser: ^4.1.2
  google_fonts: ^6.2.1
  photo_view: ^0.14.0
  video_player: ^2.9.1  # Add this line
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.0
  google_sign_in_platform_interface: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/pictures/backgroundimage.png
      - assets/pictures/intro.jpg
      - assets/logos/
      - assets/videos/logointro.mp4  # Add this line
      - assets/videos/introvid.mp4  # Add this line
      - assets/pictures/googlefavicon.png
