name: my_car_forum
description: A simple car forum web application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.0.0
  http: ^1.4.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1  # Hozzáadva hálózati képekhez
  shared_preferences: ^2.5.3   # Ha használod a nyelvi beállítások tárolására
  flutter_dotenv: ^5.2.1       # Ha környezeti változókat használsz (pl. API URL)
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/pictures/intro.jpg
      - assets/pictures/card1.jpg
      - assets/pictures/card2.jpg
      - assets/pictures/card3.jpg
      - assets/pictures/card4.jpg
      - assets/pictures/car1.jpg
      - assets/pictures/car2.jpg
      - assets/pictures/car3.jpg
      - assets/pictures/car4.jpg
      - assets/pictures/electric_cars.jpg
      - assets/pictures/suvs.jpg
      - assets/pictures/car_of_the_year.jpg
      - assets/pictures/honda_prelude.jpg      # Feature article image
      - assets/pictures/mclaren_hypercar.jpg   # Article grid image 1
      - assets/pictures/bmw_z4.jpg             # Article grid image 2
      - assets/pictures/mustang_f100.jpg       # Article grid image 3
      - assets/pictures/hummer_rivian.jpg      # Article grid image 4
      - assets/pictures/toyota_suv.jpg
      - assets/pictures/ferrari_suv.jpg
      - assets/pictures/porsche_gt3rs.jpg      # New article 1
      - assets/pictures/tesla_cybertruck.jpg   # New article 2
      - assets/pictures/audi_a9.jpg            # New article 3
      - assets/pictures/bronco_raptor.jpg      # New article 4
      - assets/pictures/lamborghini_revuelto.jpg  # New article 5
      - assets/pictures/jeep_grand_cherokee.jpg   # New article 6
      - assets/pictures/logo.png
      - assets/pictures/ferrari_future.jpg
      - assets/pictures/bmw_i8.jpg
      - assets/pictures/tesla_roadster.jpg
      - assets/pictures/lamborghini_aventador.jpg
      - assets/pictures/default_car.jpg
      - assets/logos/  # Include the logos directory for all files inside
